### ISSUE TITLE
Does the algorithm work with gaps/phantoms in the c3D file?

### ISSUE THREAD

**Issue by marnunez** [aclouthier/auto-marker-label#2]
I was wondering how this algorithm would do with unlabeled c3Ds with marker gaps and/or extra "phantom" markers product of glare against reflective surfaces and such. Does the input amount of markers has to match the amount of markers in the MarkerSet.xml or labeled c3Ds? How do you deal with that?

**Comment by aclouthier** [comment]
Yes, this will work with both gaps and phantom markers and the number of markers in the c3d does not have to match the number in the marker set (although it should use the same marker set). If there are a large number of missing or extra markers, the algorithm may be a bit less accurate.

There will be a paper that will hopefully be published soon that explains the details of how it works. Basically though, individual markers are considered based on the trajectories of the num_mks most visible markers and mean trajectories are added if there are fewer than num_mks markers.
