### ISSUE TITLE
Request: implement checkpoints

### ISSUE THREAD

**Issue by marnunez** [aclouthier/auto-marker-label#6]
Having loads of c3Ds to train and a humble laptop GPU, checkpoints would really come handy. I'm doing some tests now, but I'm not sure which objects are worth serialising with torch.save() to continue where it left, and how checkpoints should interact with prevModel. I could PR this if you're interested

**Comment by aclouthier** [comment]
I added an option to save checkpoints after each epoch and continue training from one of those checkpoints. Hope that helps!
