### ISSUE TITLE
Circular Callback from Launch

### ISSUE THREAD

**Issue by jouterleys** [aclouthier/auto-marker-label#7]
On run of markerLabelGUI.py with default settings, I get a constantly Updating GUI. It seems to be linked to an Input in the Marker label modifier Callback with the 'labels_current' input (or possibly any Callback with Input('labels_current', 'children')?

If I remove the Input('labels_current', 'children') from the Callback then the GUI loads and mostly functions. There are some issues with marker renaming and the order of operations, however, but I can create separate issues for these. I'm just not sure if they are linked to this one or not... 

```

# Marker label modifier
@app.callback([Output('message_mod','children'),Output('labels_updated','children'), Output('mod_timestamp', 'children')],
              [Input('submit-button','n_clicks')],
              [State('marker_ind', 'value'),State('new_name', 'value'), State('split_timestamp', 'children'), State('mod_timestamp', 'children')])
```

**Comment by aclouthier** [comment]
Does it happen just when running the GUI, or when you try to load in data?

**Comment by jouterleys** [comment]
Right away when running the GUI. I'm not really able to actually load/plot the data because the tab keeps Updating.

**Comment by aclouthier** [comment]
I'm not entirely sure what the problem is, because everything is working fine for me. But try changing label_current to a State instead of an input. It still seems to work for me if I do that.

```
# Marker label modifier
@app.callback([Output('message_mod','children'),Output('labels_updated','children'), Output('mod_timestamp', 'children')],
              [Input('submit-button','n_clicks')],
              [State('labels_current', 'children'), State('marker_ind', 'value'),State('new_name', 'value'), State('split_timestamp', 'children'), State('mod_timestamp', 'children')])
```

**Comment by jouterleys** [comment]
Awesome! Works for me! Thank you for the help. Super cool tool.
