### ISSUE TITLE
Accuracy of the marker label algorithm

### ISSUE THREAD

**Issue by mfalv** [aclouthier/auto-marker-label#9]
Hi,

How can I get the accuracy values pertinent to the labelling performance?

Thanks.

**Comment by aclouthier** [comment]
You need a ground truth to compare to to calculate the accuracy, so labels that have been manually verified to be correct. If you know the correct labels, you can check to see how many of the predicted labels match the correct ones across all frames of data.

**Comment by mfalv** [comment]
Is there an automatic way to retrieve the predicted labels across all frames using the GUI?

**Comment by aclouthier** [comment]
Yes, if you use the export button, it will export the data with the predicted labels to a c3d file.

**Comment by mfalv** [comment]
I used the export button but am not finding the information pertaining to the predicted labels on the c3d file. 
Could you let me know where that would be?

![image](https://user-images.githubusercontent.com/25755708/198097773-bc5aaa88-3623-4f30-89c0-8c377211e74d.png)

**Comment by aclouthier** [comment]
The marker names in the c3d file are the predicted labels. They are found under POINT->LABELS (or possibly DESCRIPTIONS).

**Comment by mfalv** [comment]
I see - thanks! The predicted labels in the c3d file correspond to one frame only?
If so, is there a more direct way to extract the label predictions across all frames instead of using the export button for each frame?

**Comment by aclouthier** [comment]
The c3d file contains every frame of data. The labels under POINTS are the labels assigned to the corresponding trajectories (through time) contained in the c3d file. c3d is a standard file format (https://www.c3d.org/) and can be imported into python using https://github.com/pyomeca/ezc3d, for example.

**Comment by mfalv** [comment]
Thanks for sending that info through!

I understand that, in order to assess the performance, the predicted and ground truth labels for the markers were compared at each frame of data - is it possible to extract the predicted labels for the markers at each frame of data?

**Comment by aclouthier** [comment]
I guess I don't understand what you are looking for. The predicted labels are what are used in the exported c3d file. It contains marker coordinates at each frame and the each marker has a label, which is the predicted label. 

If you want to compare this to ground truth, you just need to identify the matching markers based on the coordinates and compare the labels.
